name: ml
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2020.4.5.1=hecc5488_0
  - cairo=1.14.12=h8948797_3
  - certifi=2020.4.5.1=py37hc8dfbb8_0
  - cffi=1.13.2=py37h2e261b9_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - ffmpeg=4.0=hcdf2ecd_0
  - fontconfig=2.13.0=h9420a91_0
  - freeglut=3.0.0=hf484d3e_5
  - freetype=2.9.1=h8a8886c_1
  - gdk-pixbuf=2.36.9=1
  - gettext=0.19.8.1=hc5be6a0_1002
  - glib=2.56.2=had28632_1001
  - gobject-introspection=1.56.1=py37h9e29830_1001
  - graphite2=1.3.13=h23475e2_0
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hba1933b_1
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2019.4=243
  - jasper=2.0.14=h07fcdf6_1
  - joblib=0.14.1=py_0
  - jpeg=9b=h024ee3a_2
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libcroco=0.6.12=h468c787_1001
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglu=9.0.0=hf484d3e_1
  - libiconv=1.15=h516909a_1006
  - libopencv=3.4.2=hb342d67_1
  - libopus=1.3=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - librsvg=2.40.19=h84fa2a2_1000
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - libuuid=1.0.3=h1bed415_2
  - libvpx=1.7.0=h439df22_0
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - mkl=2019.4=243
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.15=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.9.0=py37hfd86e86_0
  - numpy-base=1.17.4=py37hde5b4d6_0
  - olefile=0.46=py37_0
  - opencv=3.4.2=py37h6fd60c2_1
  - openssl=1.1.1g=h516909a_0
  - pango=1.40.14=he752989_2
  - pcre=8.43=he6710b0_0
  - pillow=7.0.0=py37hb39fc2d_0
  - pip=19.3.1=py37_0
  - pixman=0.38.0=h7b6447c_0
  - py-opencv=3.4.2=py37hb342d67_1
  - pycparser=2.19=py37_0
  - python=3.7.6
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2019.3=py_0
  - readline=7.0=h7b6447c_5
  - setuptools=44.0.0=py37_0
  - six=1.13.0=py37_0
  - sqlite=3.30.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.33.6=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - absl-py==0.9.0
    - alabaster==0.7.12
    - albumentations==0.4.3
    - apex==0.1
    - appdirs==1.4.3
    - astor==0.8.1
    - attrs==19.3.0
    - babel==2.8.0
    - backcall==0.1.0
    - bcrypt==3.1.7
    - black==19.10b0
    - bleach==3.1.0
    - boto3==1.10.48
    - botocore==1.12.246
    - cached-property==1.5.1
    - cachetools==4.1.0
    - catboost==0.20.2
    - chardet==3.0.4
    - click==7.0
    - cloudpickle==1.4.1
    - colorama==0.4.3
    - commonmark==0.9.1
    - cryptography==2.9.2
    - cycler==0.10.0
    - dask==2.17.2
    - decorator==4.4.1
    - defusedxml==0.6.0
    - distributed==2.17.0
    - distro==1.5.0
    - docker==4.2.1
    - docker-compose==1.26.0
    - dockerpty==0.4.1
    - docopt==0.6.2
    - docutils==0.14
    - easydict==1.9
    - efficientnet-pytorch==0.6.3
    - entrypoints==0.3
    - fastparquet==0.3.3
    - filelock==3.0.12
    - flake8==3.7.8
    - flake8-bugbear==19.8.0
    - flask==1.1.1
    - fsspec==0.7.4
    - future==0.18.2
    - gast==0.2.2
    - gitdb2==2.0.5
    - gitpython==3.0.3
    - google-api-core==1.16.0
    - google-api-python-client==1.8.0
    - google-auth==1.13.1
    - google-auth-httplib2==0.0.3
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.1.8
    - googleapis-common-protos==1.51.0
    - grpcio==1.26.0
    - gunicorn==20.0.4
    - h5py==2.10.0
    - heapdict==1.0.1
    - httplib2==0.17.2
    - hyperopt==0.2.4
    - idna==2.8
    - imageio==2.6.1
    - imagesize==1.2.0
    - imgaug==0.2.6
    - importlib-metadata==1.3.0
    - ipykernel==5.1.3
    - ipython==7.11.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - iterative-stratification==0.1.6
    - itsdangerous==1.1.0
    - jedi==0.15.2
    - jeepney==0.4.3
    - jinja2==2.10.3
    - jmespath==0.9.4
    - json5==0.8.5
    - jsonpickle==1.4.1
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==5.3.4
    - jupyter-console==6.0.0
    - jupyter-core==4.6.1
    - jupyterlab==1.2.4
    - jupyterlab-server==1.0.6
    - kaggle==1.5.6
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - keyring==21.2.0
    - kiwisolver==1.1.0
    - lightgbm==2.3.1
    - llvmlite==0.31.0
    - locket==0.2.0
    - markdown==2.6.11
    - markupsafe==1.1.1
    - matplotlib==3.1.2
    - mccabe==0.6.1
    - mistune==0.8.4
    - more-itertools==8.0.2
    - msgpack==1.0.0
    - munch==2.5.0
    - nbconvert==5.6.1
    - nbformat==5.0.3
    - networkx==2.4
    - nltk==3.4.5
    - notebook==6.0.2
    - numba==0.48.0
    - numpy==1.18.1
    - oauth2client==4.1.3
    - oauthlib==3.1.0
    - opencv-python-headless==4.2.0.32
    - opt-einsum==3.1.0
    - packaging==20.3
    - pandas==1.0.4
    - pandocfilters==1.4.2
    - paramiko==2.7.1
    - parso==0.5.2
    - partd==1.1.0
    - pathspec==0.8.0
    - patsy==0.5.1
    - pexpect==4.7.0
    - pickleshare==0.7.5
    - pkginfo==1.5.0.1
    - plotly==4.4.1
    - pluggy==0.13.1
    - pretrainedmodels==0.7.4
    - prometheus-client==0.7.1
    - prompt-toolkit==2.0.10
    - protobuf==3.11.2
    - psutil==5.7.0
    - ptyprocess==0.6.0
    - py==1.8.1
    - py-cpuinfo==5.0.0
    - py-gfm==0.1.4
    - py-rouge==1.1
    - pyaml==20.4.0
    - pyarrow==0.16.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycodestyle==2.5.0
    - pyflakes==2.1.1
    - pygments==2.5.2
    - pynacl==1.4.0
    - pyparsing==2.4.6
    - pyrsistent==0.15.7
    - pytest==5.3.2
    - python-dotenv==0.13.0
    - python-graphviz==0.13.2
    - python-slugify==4.0.0
    - pyvips==2.1.12
    - pywavelets==1.1.1
    - pyyaml==5.3
    - pyzmq==18.1.0
    - qtconsole==4.6.0
    - readme-renderer==26.0
    - recommonmark==0.6.0
    - regex==2020.1.8
    - requests==2.22.0
    - requests-mock==1.7.0
    - requests-oauthlib==1.3.0
    - requests-toolbelt==0.9.1
    - retrying==1.3.3
    - rsa==4.0
    - s3transfer==0.2.1
    - sacred==0.8.1
    - sacremoses==0.0.38
    - sandesh==0.2
    - scikit-image==0.16.2
    - scikit-learn==0.22.1
    - scikit-optimize==0.7.4
    - scipy==1.4.1
    - seaborn==0.10.0
    - secretstorage==3.1.2
    - send2trash==1.5.0
    - sentencepiece==0.1.85
    - sh==1.12.14
    - smmap==3.0.2
    - smmap2==3.0.1
    - snowballstemmer==2.0.0
    - sortedcontainers==2.1.0
    - sphinx==2.2.0
    - sphinx-autodoc-typehints==1.10.3
    - sphinx-rtd-theme==0.4.3
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==1.0.3
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.4
    - statsmodels==0.11.1
    - subword-nmt==0.3.7
    - tblib==1.6.0
    - tensorboard==2.1.1
    - tensorflow==2.1.0
    - tensorflow-estimator==2.1.0
    - termcolor==1.1.0
    - terminado==0.8.3
    - testpath==0.4.4
    - text-unidecode==1.3
    - texttable==1.6.2
    - thrift==0.13.0
    - tokenizers==0.7.0
    - toml==0.10.0
    - toolz==0.10.0
    - torch==1.5.0
    - torchvision==0.6.1
    - tornado==6.0.3
    - tqdm==4.46.1
    - traitlets==4.3.3
    - transformers==2.11.0
    - tsfresh==0.16.0
    - twine==3.1.1
    - typed-ast==1.4.1
    - typing-extensions==3.7.4.1
    - unidecode==1.1.1
    - uritemplate==3.0.1
    - urllib3==1.24.3
    - wcwidth==0.1.8
    - webencodings==0.5.1
    - websocket-client==0.56.0
    - werkzeug==0.16.0
    - widgetsnbextension==3.5.1
    - wrapt==1.11.2
    - wtfml==0.0.3
    - xgboost==0.90
    - yawml==0.0.1
    - zict==2.0.0
    - zipp==0.6.0

