name: ml
channels:
  - defaults
dependencies:
  - ca-certificates=2020.6.24=0
  - certifi=2020.6.20=py37_0
  - libcxx=10.0.0=1
  - libedit=3.1.20191231=h1de35cc_1
  - libffi=3.3=hb1e8313_2
  - ncurses=6.2=h0a44026_1
  - openssl=1.1.1g=h1de35cc_0
  - pip=20.1.1=py37_1
  - python=3.7.7=hf48f09d_4
  - readline=8.0=h1de35cc_0
  - setuptools=46.0.0=py37_0
  - sqlite=3.32.3=hffcf06c_0
  - tk=8.6.10=hb0a8c7a_0
  - wheel=0.34.2=py37_0
  - xz=5.2.5=h1de35cc_0
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - absl-py==0.9.0
    - astunparse==1.6.3
    - attrs==19.3.0
    - bcrypt==3.1.7
    - cached-property==1.5.1
    - cachetools==4.1.1
    - cffi==1.14.0
    - chardet==3.0.4
    - click==7.1.2
    - cryptography==2.9.2
    - cycler==0.10.0
    - distro==1.5.0
    - docker==4.2.2
    - docker-compose==1.26.2
    - dockerpty==0.4.1
    - docopt==0.6.2
    - future==0.18.2
    - gast==0.3.3
    - google-auth==1.19.0
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.2.0
    - grpcio==1.30.0
    - h5py==2.10.0
    - idna==2.10
    - importlib-metadata==1.7.0
    - joblib==0.16.0
    - jsonschema==3.2.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.2.0
    - markdown==3.2.2
    - matplotlib==3.2.2
    - nltk==3.5
    - numpy==1.19.0
    - oauthlib==3.1.0
    - opt-einsum==3.2.1
    - pandas==1.0.5
    - paramiko==2.7.1
    - protobuf==3.12.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pynacl==1.4.0
    - pyparsing==2.4.7
    - pyrsistent==0.16.0
    - python-dateutil==2.8.1
    - python-dotenv==0.14.0
    - pytz==2020.1
    - pyyaml==5.3.1
    - regex==2020.6.8
    - requests==2.24.0
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - scikit-learn==0.23.1
    - scipy==1.4.1
    - seaborn==0.10.1
    - six==1.15.0
    - tensorboard==2.2.2
    - tensorboard-plugin-wit==1.7.0
    - tensorflow==2.2.0
    - tensorflow-estimator==2.2.0
    - termcolor==1.1.0
    - texttable==1.6.2
    - threadpoolctl==2.1.0
    - torch==1.5.1
    - tqdm==4.47.0
    - urllib3==1.25.9
    - websocket-client==0.57.0
    - werkzeug==1.0.1
    - wrapt==1.12.1
    - zipp==3.1.0

